name: Deploy to Staging Environment
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
jobs:
  Deploy-Staging:
    if: |
      github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build and Compile Typescript
        run: yarn build
      - name: Deploy to Heroku Staging Environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'governator-api-test'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: develop
        env:
          HD_DISCORD_CLIENT_ID: ${{secrets.QA_DISCORD_CLIENT_ID}}
          HD_DISCORD_CLIENT_SECRET: ${{secrets.QA_DISCORD_CLIENT_SECRET}}
          HD_DISCORD_CALLBACK_URL: ${{secrets.QA_DISCORD_CALLBACK_URL}}
          HD_DISCORD_OAUTH_SCOPES: ${{secrets.QA_DISCORD_OAUTH_SCOPES}}
          HD_SESSION_SECRET: ${{secrets.QA_SESSION_SECRET}}
          HD_FE_HOST: ${{secrets.QA_FE_HOST}}
          HD_REDIS_URL: ${{secrets.QA_REDIS_URL}}         
          HD_ALCHEMY_API_KEY_ETHEREUM_MAIN: ${{secrets.ALCHEMY_API_KEY_ETHEREUM_MAIN}}
          HD_ALCHEMY_API_KEY_POLYGON_MAIN: ${{secrets.ALCHEMY_API_KEY_POLYGON_MAIN}}
          HD_API_GLOBAL_PREFIX: ${{vars.GOVERNATOR_API_GLOBAL_PREFIX}}
          HD_API_KEY: ${{secrets.QA_GOVERNATOR_API_KEY}}
          HD_API_PORT: ${{vars.GOVERNATOR_API_PORT}}
          HD_CACHE: ${{vars.QA_CACHE}}
          HD_CORS_ORIGIN: ${{vars.QA_CORS_ORIGIN}}
          HD_ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
          HD_INFURA_ETHEREUM_MAIN_ID: ${{secrets.INFURA_ETHEREUM_MAIN_ID}}
          HD_INFURA_ETHEREUM_MAIN_SECRET: ${{secrets.INFURA_ETHEREUM_MAIN_SECRET}}
          HD_MONGODB_CLUSTER: ${{secrets.QA_MONGODB_CLUSTER}}
          HD_MONGODB_DATABASE: ${{secrets.QA_MONGODB_DATABASE}}
          HD_MONGODB_PASS: ${{secrets.QA_MONGODB_PASS}}
          HD_MONGODB_PREFIX: ${{secrets.QA_MONGODB_PREFIX}}
          HD_MONGODB_USERNAME: ${{secrets.QA_MONGODB_USERNAME}}
          HD_MONGO_LOCAL: ""
          HD_REDIS_HOST_QUEUE: ${{secrets.QA_REDIS_HOST_QUEUE}}
          HD_REDIS_PASSWORD_QUEUE: ${{secrets.QA_REDIS_PASSWORD_QUEUE}}
          HD_REDIS_PORT_QUEUE: ${{secrets.QA_REDIS_PORT_QUEUE}}
          HD_REDIS_USERNAME_QUEUE: ${{secrets.QA_REDIS_USERNAME_QUEUE}}